// import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-icons/font/bootstrap-icons.min.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Instrumentacion Didactica ISIC',
  description: 'Generated by create next app',
  author : 'TEPP',
  carrer : 'ISIC'
}

export default function RootLayout({ children }) {
  return (
    <html lang="es-mx">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
